---
# file : roles/chat_server/tasks/certbot.yaml

- name: Restart service httpd
  remote_user: ubuntu
  become: yes
  become_method: sudo
  service:
    name: nginx
    state: started

- name: install certbot
  remote_user: ubuntu
  become: yes
  become_method: sudo
  command:
    cmd: snap install --beta --classic certbot
  when: have_fqdn == True

- name: run certbot
  remote_user: ubuntu
  become: yes
  become_method: sudo
  command:
    cmd: certbot certonly --webroot -w /var/www/html -m all@200013.net --agree-tos -n  -d "{{ my_fqdn }}"
  when: have_fqdn == True
