# file : roles/chat_server/tasks/install_templates.yaml

- name: create template dir
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: /home/app/templates
    state: directory
    owner: www-data
    group: www-data
    mode: 0400

- name: create js subfolder in template dir
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: /home/app/templates/js
    state: directory
    owner: app
    group: www-data
    mode: 0550

- name: create messages subfolder in template dir
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: /home/app/templates/messages
    state: directory
    owner: app
    group: www-data
    mode: 0750

- name : add template chat
  remote_user: ubuntu
  become: yes
  become_method: sudo
  template:
    src: roles/chat_server/files/templates/chat.j2
    dest: /home/app/templates/chat.html
    owner: www-data
    group: www-data
    mode: 0400

- name : add updates.json 
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy:
    src: roles/chat_server/files/templates/updates.json
    dest: /home/app/templates/
    owner: www-data
    group: www-data
    mode: 0400

- name : add icon
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy:
    src: roles/chat_server/files/templates/tc.ico
    dest: /home/app/templates/
    owner: www-data
    group: www-data
    mode: 0400

- name : copy css 
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy:
    src: roles/chat_server/files/templates/css
    dest: /home/app/templates/
    owner: www-data
    group: www-data
    mode: 0400

- name : create chat_custom.js from template 
  remote_user: ubuntu
  become: yes
  become_method: sudo
  template:
    src: roles/chat_server/files/templates/js/chat_custom.js.j2
    dest: /home/app/templates/js/chat_custom.js
    owner: www-data
    group: www-data
    mode: 0440

- name : copy icons
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy:
    src: roles/chat_server/files/templates/icons
    dest: /home/app/templates/
    owner: www-data
    group: www-data
    mode: 0400

