# file : roles/chat_server/tasks/install_templates.yaml

- name: create template dir
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: /home/app/templates
    state: directory
    owner: www-data
    group: www-data
    mode: 0400

- name : add template chat
  remote_user: ubuntu
  become: yes
  become_method: sudo
  template:
    src: roles/chat_server/files/templates/chat.j2
    dest: /home/app/templates/chat.html
    owner: www-data
    group: www-data
    mode: 0400

- name : add version.txt
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy:
    src: roles/chat_server/files/templates/version.txt
    dest: /home/app/templates/
    owner: www-data
    group: www-data
    mode: 0400

- name : add icon
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy:
    src: roles/chat_server/files/templates/tc.ico
    dest: /home/app/templates/
    owner: www-data
    group: www-data
    mode: 0400

- name : copy css 
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy:
    src: roles/chat_server/files/templates/css
    dest: /home/app/templates/
    owner: www-data
    group: www-data
    mode: 0400


- name : copy js 
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy:
    src: roles/chat_server/files/templates/js
    dest: /home/app/templates/
    owner: www-data
    group: www-data
    mode: 0400

- name : create chat_custom.js from template 
  remote_user: ubuntu
  become: yes
  become_method: sudo
  template:
    src: roles/chat_server/files/templates/js/chat_custom.js.j2
    dest: /home/app/templates/js/chat_custom.js
    owner: www-data
    group: www-data
    mode: 0440

- name : copy icons
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy:
    src: roles/chat_server/files/templates/icons
    dest: /home/app/templates/
    owner: www-data
    group: www-data
    mode: 0400

- name : copy conversation.html
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy:
    src: roles/chat_server/files/templates/conversation.html
    dest: /home/app/templates/
    owner: www-data
    group: www-data
    mode: 0400

- name : copy html_top
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy:
    src: roles/chat_server/files/templates/html_top
    dest: /home/app/templates/
    owner: www-data
    group: www-data
    mode: 0400

- name : copy messages
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy:
    src: roles/chat_server/files/templates/messages
    dest: /home/app/templates/
    owner: www-data
    group: www-data
    mode: 0400

- name : copy html_bottom
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy:
    src: roles/chat_server/files/templates/html_bottom
    dest: /home/app/templates/
    owner: www-data
    group: www-data
    mode: 0400
