---
# file : roles/common/tasks/configure_nginx.yaml

- name: copy nginx main configuration file
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy:
    src: roles/common/files/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: copy nginx [my_fqdn] in sites-available
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy:
    src: {{ 'roles/common/files/nginx/' + my_fqdn }}
    dest: /etc/nginx/sites-available
    owner: root
    group: root
    mode: 0644

- name: symlink sites-available/[my_fqdn] -> sites-enabled/[my_fqdn]
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    src: {{ '/etc/nginx/sites-available/' + my_fqdn }}
    dest: {{ '/etc/nginx/sites-enabled/' + my_fqdn }}
    owner: root
    group: root
    state: link

