---
# file : roles/chat_server/tasks/copy_files.yaml

- name: create /var/www/[my_fqdn]/
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: "{{ '/var/www/' + my_fqdn + '/' }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0500

- name: create /var/www/[my_fqdn]/html
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: "{{ '/var/www/' + my_fqdn + '/html' }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0500

- name: create main website from template
  remote_user: ubuntu
  become: yes
  become_method: sudo
  template:
    src: roles/chat_server/files/html/index.html.j2
    dest: "{{ '/var/www/' + my_fqdn + '/html/index.html' }}"
    owner: www-data
    group: www-data
    mode: 0400

- name: copy html files
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy: 
    src: roles/chat_server/files/html/*
    dest: "{{ '/var/www/' + my_fqdn + '/' }}"
    owner: www-data
    group: www-data
    mode: 0400
  when: my_fqdn == "temporary.chat"

- name: copy css for the spinner
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy: 
    src: roles/chat_server/files/html/spinner.css
    dest: "{{ '/var/www/' + my_fqdn + '/html/spinner.css' }}"
    owner: www-data
    group: www-data
    mode: 0400

- name: copy jquery
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy: 
    src: roles/chat_server/files/html/jquery.min.js
    dest: "{{ '/var/www/' + my_fqdn + '/html/jquery.min.js' }}"
    owner: www-data
    group: www-data
    mode: 0400

- name: create /var/www/[my_fqdn]/app
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: "{{ '/var/www/' + my_fqdn + '/app' }}"
    state: directory
    owner: app
    group: app
    mode: 0755

- name: create app.ini
  remote_user: ubuntu
  become: yes
  become_method: sudo
  template:
    src: roles/chat_server/files/app/app.ini.j2
    dest: "{{ '/var/www/' + my_fqdn + '/app/app.ini' }}"
    owner: app
    group: app
    mode: 0400

- name: create app.py
  remote_user: ubuntu
  become: yes
  become_method: sudo
  template:
    src: roles/chat_server/files/app/app.py.j2
    dest: "{{ '/var/www/' + my_fqdn + '/app/app.py' }}"
    owner: app
    group: app
    mode: 0400

- name: copy create_room.sh
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy:
    src: roles/chat_server/files/app/create_room.sh
    dest: "{{ '/var/www/' + my_fqdn + '/app/create_room.sh' }}"
    owner: app 
    group: app
    mode: 0770

- name: copy destroy_room.sh
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy:
    src: roles/chat_server/files/app/destroy_room.sh
    dest: "{{ '/var/www/' + my_fqdn + '/app/destroy_room.sh' }}"
    owner: app 
    group: app
    mode: 0770


- name: create /var/www/[my_fqdn]/app/rooms
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: "{{ '/var/www/' + my_fqdn + '/app/rooms' }}"
    state: directory
    owner: app
    group: www-data
    mode: 0770

