---
# file: roles/chat_server/tasks/enable_restart_service.yaml

- name: Restart service httpd
  remote_user: ubuntu
  become: yes
  become_method: sudo
  service:
    name: nginx
    state: restarted

- name: Restart service uwsgi
  remote_user: ubuntu
  become: yes
  become_method: sudo
  service:
    name: uwsgi
    state: restarted

- name: Restart service httpd
  remote_user: ubuntu
  become: yes
  become_method: sudo
  service:
    name: nginx
    enabled: yes

- name: Restart service uwsgi
  remote_user: ubuntu
  become: yes
  become_method: sudo
  service:
    name: uwsgi
    enabled: yes

