---
# name: roles/chat_server/tasks/folders_and_files.yaml
- name: Create /var/log/uwsgi
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: /var/log/uwsgi
    state: directory
    owner: app 
    group: app
    mode: 0775

- name: Create /var/log/uwsgi/app.log
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: /var/log/uwsgi/app.log
    state: touch
    owner: app 
    group: app
    mode: 0664

- name: Create /var/www/[my_fqdn]
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: "{{ '/var/www/' + my_fqdn }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: Create /var/www/[my_fqdn]/app
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: "{{ '/var/www/' + my_fqdn + '/app' }}"
    state: directory
    owner: app
    group: app
    mode: 0755

- name: Create /var/www/[my_fqdn]/app/passwds
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: "{{ '/var/www/' + my_fqdn + '/app/passwds' }}"
    state: directory
    owner: app
    group: app
    mode: 0755

- name: Create /var/www/[my_fqdn]/app/rooms
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: "{{ '/var/www/' + my_fqdn + '/app/rooms' }}"
    state: directory
    owner: app
    group: www-data
    mode: 0770


- name: Create /var/www/[my_fqdn]/app/sites
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: "{{ '/var/www/' + my_fqdn + '/app/sites' }}"
    state: directory
    owner: app
    group: app
    mode: 0775

- name: Create a symbolic link /var/www/[my_fqdn]/html/rooms -> /var/www/[my_fqdn]/app/rooms
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    src: "{{ '/var/www/' + my_fqdn + '/app/rooms' }}"
    dest: "{{ '/var/www/' + my_fqdn + '/html/rooms' }}"
    owner: app
    group: www-data
    state: link

- name: Create a app socket in /var/www/[my_fqdn]/app/app.sock
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: "{{ '/var/www/' + my_fqdn + '/app/app.sock' }}"
    state: touch
    owner: app
    group: www-data
    mode: 4664

