---

- name: create /var/www/[my_fqdn]/
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: "{{ '/var/www/' + my_fqdn + '/' }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: create /var/www/[my_fqdn]/html
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: "{{ '/var/www/' + my_fqdn + '/html' }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0500


- name: add extra html files if domain is temporary.chat
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy: 
    src: roles/chat_server/files/html
    dest: "{{ '/var/www/' + my_fqdn + '/' }}"
    owner: www-data
    group: www-data
    mode: 0400
  when: my_fqdn == "temporary.chat"

- name: create main website from template
  remote_user: ubuntu
  become: yes
  become_method: sudo
  template:
    src: roles/chat_server/files/html/index.html.j2
    dest: "{{ '/var/www/' + my_fqdn + '/html/index.html' }}"
    owner: www-data
    group: www-data
    mode: 0400
  when: multirooms == True

- name: copy css for the spinner
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy: 
    src: roles/chat_server/files/html/spinner.css
    dest: "{{ '/var/www/' + my_fqdn + '/html/spinner.css' }}"
    owner: www-data
    group: www-data
    mode: 0400
  when: multirooms == True

- name: copy jquery
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy: 
    src: roles/chat_server/files/html/jquery.min.js
    dest: "{{ '/var/www/' + my_fqdn + '/html/jquery.min.js' }}"
    owner: www-data
    group: www-data
    mode: 0400
  when: multirooms == True

- name: copy single chat room
  remote_user: ubuntu
  become: yes
  become_method: sudo
  template:
    src: roles/chat_server/files/templates/chat.j2
    dest: "{{ '/var/www/' + my_fqdn + '/html/index.html' }}"
    owner: www-data
    group: www-data
    mode: 0400
  when: multirooms == False 
 
- name: copy single chat room css
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy:
    src: roles/chat_server/files/templates/css
    dest: "{{ '/var/www/' + my_fqdn + '/html/' }}"
    owner: www-data
    group: www-data
    mode: 0400
  when: multirooms == False 

- name: copy single chat room js
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy:
    src: roles/chat_server/files/templates/js
    dest: "{{ '/var/www/' + my_fqdn + '/html/' }}"
    owner: www-data
    group: www-data
    mode: 0400
  when: multirooms == False 

- name: copy single chat room js
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy:
    src: roles/chat_server/files/templates/js
    dest: "{{ '/var/www/' + my_fqdn + '/html/' }}"
    owner: www-data
    group: www-data
    mode: 0400
  when: multirooms == False 

- name: create single room folder
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: "{{ '/var/www/' + my_fqdn + '/app/rooms/' + my_fqdn }}"
    state: directory
    owner: app
    group: www-data
    mode: 0750
  when: multirooms == False 

- name: create conversation.txt file for single room
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: "{{ '/var/www/' + my_fqdn + '/app/rooms/' + my_fqdn + '/conversation.txt' }}"
    state: touch
    owner: app
    group: www-data
    mode: 0646
  when: multirooms == False 

- name: create symlink between app/conversation.txt and html/conversation.txt file for single room
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    src: "{{ '/var/www/' + my_fqdn + '/app/rooms/' + my_fqdn + '/conversation.txt' }}"
    dest: "{{ '/var/www/' + my_fqdn + '/html/conversation.txt' }}"
    state: link
  when: multirooms == False 

- name: create upload folder for single room
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: "{{ '/var/www/' + my_fqdn + '/app/rooms/' + my_fqdn + '/files' }}"
    state: directory
    owner: app
    group: www-data
    mode: 0750
  when: multirooms == False 

- name: create symlink to uplaod folder for single room
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    src: "{{ '/var/www/' + my_fqdn + '/app/rooms/' + my_fqdn + '/files' }}"
    dest: "{{ '/var/www/' + my_fqdn + '/html/files' }}"
    state: link
  when: multirooms == False 
