---

- name: create /var/www/[my_fqdn]/
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: "{{ '/var/www/' + my_fqdn + '/' }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: create /var/www/[my_fqdn]/html
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: "{{ '/var/www/' + my_fqdn + '/html' }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0500


- name: add extra html files if domain is temporary.chat
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy: 
    src: roles/chat_server/files/html
    dest: "{{ '/var/www/' + my_fqdn + '/' }}"
    owner: www-data
    group: www-data
    mode: 0400
  when: my_fqdn == "temporary.chat"

- name: create main website from template
  remote_user: ubuntu
  become: yes
  become_method: sudo
  template:
    src: roles/chat_server/files/html/index.html.j2
    dest: "{{ '/var/www/' + my_fqdn + '/html/index.html' }}"
    owner: www-data
    group: www-data
    mode: 0400

- name: copy css for the spinner
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy: 
    src: roles/chat_server/files/html/spinner.css
    dest: "{{ '/var/www/' + my_fqdn + '/html/spinner.css' }}"
    owner: www-data
    group: www-data
    mode: 0400

- name: copy jquery
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy: 
    src: roles/chat_server/files/html/jquery.min.js
    dest: "{{ '/var/www/' + my_fqdn + '/html/jquery.min.js' }}"
    owner: www-data
    group: www-data
    mode: 0400
