# file : roles/chat_server/tasks/install_scripts.yaml

- name: install room-master.sh
  remote_user: ubuntu
  become: yes
  become_method: sudo
  template: 
    src: roles/chat_server/files/root/room-master.sh.j2
    dest: /root/room-master.sh
    owner: root
    group: root
    mode: 0700

- name: install cleanup-destroyed-rooms.sh
  remote_user: ubuntu
  become: yes
  become_method: sudo
  template: 
    src: roles/chat_server/files/root/cleanup-destroyed-rooms.sh.j2
    dest: /root/cleanup-destroyed-rooms
    owner: root
    group: root
    mode: 0700
