---
# file: packages.yaml
- name: install all system packages 
  become: yes
  become_method: sudo
  apt:
    pkg:
      - net-tools
      - nginx
      - zip
      - python3-dev
      - python3-pip
      - python3-virtualenv
      - snapd
    state: present
    update_cache: true

