---

- name: create a systemd unit file for uwsgi
  remote_user: ubuntu
  become: yes
  become_method: sudo
  template:
    src: roles/chat_server/files/systemd/uwsgi.service.j2 
    dest: /etc/systemd/system/uwsgi.service
    owner: root
    group: root
    mode: 0644

