---
# file : roles/common/tasks/copy_files.yaml
- name: copy html files
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy: 
    src: roles/common/files/html
    dest: /var/www/temporary.chat/
    owner: www-data
    group: www-data
    mode: 0400

- name: copy app files
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy:
    src: roles/common/files/app
    dest: /var/www/temporary.chat/
    owner: app
    group: app
    mode: 0400

- name: fix permissions on /var/www/temporary.chat/app/rooms
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: /var/www/temporary.chat/app/rooms
    state: directory
    owner: app
    group: www-data
    mode: 0770

