---
# name: roles/common/tasks/folders_and_files.yaml
- name: Create /var/log/uwsgi
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: /var/log/uwsgi
    state: directory
    owner: app 
    group: app
    mode: 0775

- name: Create /var/log/uwsgi/app.log
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: /var/log/uwsgi/app.log
    state: touch
    owner: app 
    group: app
    mode: 0664

- name: Create /var/www/temporary.chat
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: /var/www/temporary.chat
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

    #- name: Create /var/www/temporary.chat/html
    #remote_user: ubuntu
    # become: yes
    #become_method: sudo
    #file:
    #path: /var/www/temporary.chat/html
    #state: directory
    #owner: www-data
    #group: app
    #mode: 0775

- name: Create /var/www/temporary.chat/app
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: /var/www/temporary.chat/app
    state: directory
    owner: app
    group: app
    mode: 0755

- name: Create /var/www/temporary.chat/app/passwds
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: /var/www/temporary.chat/app/passwds
    state: directory
    owner: app
    group: app
    mode: 0755

- name: Create /var/www/temporary.chat/app/rooms
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: /var/www/temporary.chat/app/rooms
    state: directory
    owner: app
    group: www-data
    mode: 0770


- name: Create /var/www/temporary.chat/app/sites
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: /var/www/temporary.chat/app/sites
    state: directory
    owner: app
    group: app
    mode: 0775

- name: Create a symbolic link /var/www/temporary.chat/html/rooms -> /var/www/temporary.chat/app/rooms
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    src: /var/www/temporary.chat/app/rooms
    dest: /var/www/temporary.chat/html/rooms
    owner: app
    group: www-data
    state: link

- name: Create a app socket in /var/www/temporary.chat/app/app.sock
  remote_user: ubuntu
  become: yes
  become_method: sudo
  file:
    path: /var/www/temporary.chat/app/app.sock
    state: touch
    owner: app
    group: www-data
    mode: 4664

