---
# file : roles/common/tasks/systemd.yaml
- name: copy uwsgi systemd unit file
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy: 
    src: roles/common/files/systemd/uwsgi.service
    dest: /etc/systemd/system/uwsgi.service
    owner: root
    group: root
    mode: 0644

- name: copy room_master systemd unit file
  remote_user: ubuntu
  become: yes
  become_method: sudo
  copy: 
    src: roles/common/files/systemd/room_master.service
    dest: /etc/systemd/system/room_master.service
    owner: root
    group: root
    mode: 0644
